/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Property type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Property{}

// Property struct for Property
type Property struct {
	Address Address `json:"address"`
	Building Building `json:"building"`
	CreatedAt time.Time `json:"created_at"`
	Description *string `json:"description,omitempty"`
	Energy *Energy `json:"energy,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	Id string `json:"id"`
	Images []Image `json:"images,omitempty"`
	LastVerifiedAt *time.Time `json:"last_verified_at,omitempty"`
	Listing *Listing `json:"listing,omitempty"`
	Location *Location `json:"location,omitempty"`
	Market *MarketContext `json:"market,omitempty"`
	PriceHistory []PriceObservation `json:"price_history,omitempty"`
	Rooms Rooms `json:"rooms"`
	Size Size `json:"size"`
	Source string `json:"source"`
	Title string `json:"title"`
	Type string `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _Property Property

// NewProperty instantiates a new Property object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProperty(address Address, building Building, createdAt time.Time, id string, rooms Rooms, size Size, source string, title string, type_ string, updatedAt time.Time) *Property {
	this := Property{}
	this.Address = address
	this.Building = building
	this.CreatedAt = createdAt
	this.Id = id
	this.Rooms = rooms
	this.Size = size
	this.Source = source
	this.Title = title
	this.Type = type_
	this.UpdatedAt = updatedAt
	return &this
}

// NewPropertyWithDefaults instantiates a new Property object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPropertyWithDefaults() *Property {
	this := Property{}
	return &this
}

// GetAddress returns the Address field value
func (o *Property) GetAddress() Address {
	if o == nil {
		var ret Address
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Property) GetAddressOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Property) SetAddress(v Address) {
	o.Address = v
}

// GetBuilding returns the Building field value
func (o *Property) GetBuilding() Building {
	if o == nil {
		var ret Building
		return ret
	}

	return o.Building
}

// GetBuildingOk returns a tuple with the Building field value
// and a boolean to check if the value has been set.
func (o *Property) GetBuildingOk() (*Building, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Building, true
}

// SetBuilding sets field value
func (o *Property) SetBuilding(v Building) {
	o.Building = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Property) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Property) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Property) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Property) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Property) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Property) SetDescription(v string) {
	o.Description = &v
}

// GetEnergy returns the Energy field value if set, zero value otherwise.
func (o *Property) GetEnergy() Energy {
	if o == nil || IsNil(o.Energy) {
		var ret Energy
		return ret
	}
	return *o.Energy
}

// GetEnergyOk returns a tuple with the Energy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetEnergyOk() (*Energy, bool) {
	if o == nil || IsNil(o.Energy) {
		return nil, false
	}
	return o.Energy, true
}

// HasEnergy returns a boolean if a field has been set.
func (o *Property) HasEnergy() bool {
	if o != nil && !IsNil(o.Energy) {
		return true
	}

	return false
}

// SetEnergy gets a reference to the given Energy and assigns it to the Energy field.
func (o *Property) SetEnergy(v Energy) {
	o.Energy = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *Property) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *Property) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *Property) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetId returns the Id field value
func (o *Property) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Property) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Property) SetId(v string) {
	o.Id = v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *Property) GetImages() []Image {
	if o == nil || IsNil(o.Images) {
		var ret []Image
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetImagesOk() ([]Image, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *Property) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []Image and assigns it to the Images field.
func (o *Property) SetImages(v []Image) {
	o.Images = v
}

// GetLastVerifiedAt returns the LastVerifiedAt field value if set, zero value otherwise.
func (o *Property) GetLastVerifiedAt() time.Time {
	if o == nil || IsNil(o.LastVerifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastVerifiedAt
}

// GetLastVerifiedAtOk returns a tuple with the LastVerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetLastVerifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastVerifiedAt) {
		return nil, false
	}
	return o.LastVerifiedAt, true
}

// HasLastVerifiedAt returns a boolean if a field has been set.
func (o *Property) HasLastVerifiedAt() bool {
	if o != nil && !IsNil(o.LastVerifiedAt) {
		return true
	}

	return false
}

// SetLastVerifiedAt gets a reference to the given time.Time and assigns it to the LastVerifiedAt field.
func (o *Property) SetLastVerifiedAt(v time.Time) {
	o.LastVerifiedAt = &v
}

// GetListing returns the Listing field value if set, zero value otherwise.
func (o *Property) GetListing() Listing {
	if o == nil || IsNil(o.Listing) {
		var ret Listing
		return ret
	}
	return *o.Listing
}

// GetListingOk returns a tuple with the Listing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetListingOk() (*Listing, bool) {
	if o == nil || IsNil(o.Listing) {
		return nil, false
	}
	return o.Listing, true
}

// HasListing returns a boolean if a field has been set.
func (o *Property) HasListing() bool {
	if o != nil && !IsNil(o.Listing) {
		return true
	}

	return false
}

// SetListing gets a reference to the given Listing and assigns it to the Listing field.
func (o *Property) SetListing(v Listing) {
	o.Listing = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Property) GetLocation() Location {
	if o == nil || IsNil(o.Location) {
		var ret Location
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetLocationOk() (*Location, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Property) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given Location and assigns it to the Location field.
func (o *Property) SetLocation(v Location) {
	o.Location = &v
}

// GetMarket returns the Market field value if set, zero value otherwise.
func (o *Property) GetMarket() MarketContext {
	if o == nil || IsNil(o.Market) {
		var ret MarketContext
		return ret
	}
	return *o.Market
}

// GetMarketOk returns a tuple with the Market field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetMarketOk() (*MarketContext, bool) {
	if o == nil || IsNil(o.Market) {
		return nil, false
	}
	return o.Market, true
}

// HasMarket returns a boolean if a field has been set.
func (o *Property) HasMarket() bool {
	if o != nil && !IsNil(o.Market) {
		return true
	}

	return false
}

// SetMarket gets a reference to the given MarketContext and assigns it to the Market field.
func (o *Property) SetMarket(v MarketContext) {
	o.Market = &v
}

// GetPriceHistory returns the PriceHistory field value if set, zero value otherwise.
func (o *Property) GetPriceHistory() []PriceObservation {
	if o == nil || IsNil(o.PriceHistory) {
		var ret []PriceObservation
		return ret
	}
	return o.PriceHistory
}

// GetPriceHistoryOk returns a tuple with the PriceHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Property) GetPriceHistoryOk() ([]PriceObservation, bool) {
	if o == nil || IsNil(o.PriceHistory) {
		return nil, false
	}
	return o.PriceHistory, true
}

// HasPriceHistory returns a boolean if a field has been set.
func (o *Property) HasPriceHistory() bool {
	if o != nil && !IsNil(o.PriceHistory) {
		return true
	}

	return false
}

// SetPriceHistory gets a reference to the given []PriceObservation and assigns it to the PriceHistory field.
func (o *Property) SetPriceHistory(v []PriceObservation) {
	o.PriceHistory = v
}

// GetRooms returns the Rooms field value
func (o *Property) GetRooms() Rooms {
	if o == nil {
		var ret Rooms
		return ret
	}

	return o.Rooms
}

// GetRoomsOk returns a tuple with the Rooms field value
// and a boolean to check if the value has been set.
func (o *Property) GetRoomsOk() (*Rooms, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rooms, true
}

// SetRooms sets field value
func (o *Property) SetRooms(v Rooms) {
	o.Rooms = v
}

// GetSize returns the Size field value
func (o *Property) GetSize() Size {
	if o == nil {
		var ret Size
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *Property) GetSizeOk() (*Size, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *Property) SetSize(v Size) {
	o.Size = v
}

// GetSource returns the Source field value
func (o *Property) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *Property) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *Property) SetSource(v string) {
	o.Source = v
}

// GetTitle returns the Title field value
func (o *Property) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Property) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Property) SetTitle(v string) {
	o.Title = v
}

// GetType returns the Type field value
func (o *Property) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Property) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Property) SetType(v string) {
	o.Type = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Property) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Property) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Property) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Property) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Property) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["building"] = o.Building
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Energy) {
		toSerialize["energy"] = o.Energy
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Images) {
		toSerialize["images"] = o.Images
	}
	if !IsNil(o.LastVerifiedAt) {
		toSerialize["last_verified_at"] = o.LastVerifiedAt
	}
	if !IsNil(o.Listing) {
		toSerialize["listing"] = o.Listing
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Market) {
		toSerialize["market"] = o.Market
	}
	if !IsNil(o.PriceHistory) {
		toSerialize["price_history"] = o.PriceHistory
	}
	toSerialize["rooms"] = o.Rooms
	toSerialize["size"] = o.Size
	toSerialize["source"] = o.Source
	toSerialize["title"] = o.Title
	toSerialize["type"] = o.Type
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Property) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"building",
		"created_at",
		"id",
		"rooms",
		"size",
		"source",
		"title",
		"type",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProperty := _Property{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProperty)

	if err != nil {
		return err
	}

	*o = Property(varProperty)

	return err
}

type NullableProperty struct {
	value *Property
	isSet bool
}

func (v NullableProperty) Get() *Property {
	return v.value
}

func (v *NullableProperty) Set(val *Property) {
	v.value = val
	v.isSet = true
}

func (v NullableProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProperty(val *Property) *NullableProperty {
	return &NullableProperty{value: val, isSet: true}
}

func (v NullableProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


