/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InquiryPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InquiryPage{}

// InquiryPage A page of Inquiry records, with the cursor for the next one.
type InquiryPage struct {
	Data []Inquiry `json:"data"`
	Meta *PageMeta `json:"meta,omitempty"`
}

type _InquiryPage InquiryPage

// NewInquiryPage instantiates a new InquiryPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInquiryPage(data []Inquiry) *InquiryPage {
	this := InquiryPage{}
	this.Data = data
	return &this
}

// NewInquiryPageWithDefaults instantiates a new InquiryPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInquiryPageWithDefaults() *InquiryPage {
	this := InquiryPage{}
	return &this
}

// GetData returns the Data field value
func (o *InquiryPage) GetData() []Inquiry {
	if o == nil {
		var ret []Inquiry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InquiryPage) GetDataOk() ([]Inquiry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *InquiryPage) SetData(v []Inquiry) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *InquiryPage) GetMeta() PageMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PageMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiryPage) GetMetaOk() (*PageMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *InquiryPage) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PageMeta and assigns it to the Meta field.
func (o *InquiryPage) SetMeta(v PageMeta) {
	o.Meta = &v
}

func (o InquiryPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InquiryPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

func (o *InquiryPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInquiryPage := _InquiryPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInquiryPage)

	if err != nil {
		return err
	}

	*o = InquiryPage(varInquiryPage)

	return err
}

type NullableInquiryPage struct {
	value *InquiryPage
	isSet bool
}

func (v NullableInquiryPage) Get() *InquiryPage {
	return v.value
}

func (v *NullableInquiryPage) Set(val *InquiryPage) {
	v.value = val
	v.isSet = true
}

func (v NullableInquiryPage) IsSet() bool {
	return v.isSet
}

func (v *NullableInquiryPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInquiryPage(val *InquiryPage) *NullableInquiryPage {
	return &NullableInquiryPage{value: val, isSet: true}
}

func (v NullableInquiryPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInquiryPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


