/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportResponse{}

// ImportResponse One Import.
type ImportResponse struct {
	Data Import `json:"data"`
}

type _ImportResponse ImportResponse

// NewImportResponse instantiates a new ImportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportResponse(data Import) *ImportResponse {
	this := ImportResponse{}
	this.Data = data
	return &this
}

// NewImportResponseWithDefaults instantiates a new ImportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportResponseWithDefaults() *ImportResponse {
	this := ImportResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ImportResponse) GetData() Import {
	if o == nil {
		var ret Import
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ImportResponse) GetDataOk() (*Import, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ImportResponse) SetData(v Import) {
	o.Data = v
}

func (o ImportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ImportResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportResponse := _ImportResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportResponse)

	if err != nil {
		return err
	}

	*o = ImportResponse(varImportResponse)

	return err
}

type NullableImportResponse struct {
	value *ImportResponse
	isSet bool
}

func (v NullableImportResponse) Get() *ImportResponse {
	return v.value
}

func (v *NullableImportResponse) Set(val *ImportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportResponse(val *ImportResponse) *NullableImportResponse {
	return &NullableImportResponse{value: val, isSet: true}
}

func (v NullableImportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


