/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SeriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SeriesResponse{}

// SeriesResponse One Series.
type SeriesResponse struct {
	Data Series `json:"data"`
}

type _SeriesResponse SeriesResponse

// NewSeriesResponse instantiates a new SeriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSeriesResponse(data Series) *SeriesResponse {
	this := SeriesResponse{}
	this.Data = data
	return &this
}

// NewSeriesResponseWithDefaults instantiates a new SeriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSeriesResponseWithDefaults() *SeriesResponse {
	this := SeriesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *SeriesResponse) GetData() Series {
	if o == nil {
		var ret Series
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SeriesResponse) GetDataOk() (*Series, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SeriesResponse) SetData(v Series) {
	o.Data = v
}

func (o SeriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SeriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SeriesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSeriesResponse := _SeriesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSeriesResponse)

	if err != nil {
		return err
	}

	*o = SeriesResponse(varSeriesResponse)

	return err
}

type NullableSeriesResponse struct {
	value *SeriesResponse
	isSet bool
}

func (v NullableSeriesResponse) Get() *SeriesResponse {
	return v.value
}

func (v *NullableSeriesResponse) Set(val *SeriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSeriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSeriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeriesResponse(val *SeriesResponse) *NullableSeriesResponse {
	return &NullableSeriesResponse{value: val, isSet: true}
}

func (v NullableSeriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


