/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookList{}

// WebhookList Every Webhook record.
type WebhookList struct {
	Data []Webhook `json:"data"`
}

type _WebhookList WebhookList

// NewWebhookList instantiates a new WebhookList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookList(data []Webhook) *WebhookList {
	this := WebhookList{}
	this.Data = data
	return &this
}

// NewWebhookListWithDefaults instantiates a new WebhookList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookListWithDefaults() *WebhookList {
	this := WebhookList{}
	return &this
}

// GetData returns the Data field value
func (o *WebhookList) GetData() []Webhook {
	if o == nil {
		var ret []Webhook
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebhookList) GetDataOk() ([]Webhook, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *WebhookList) SetData(v []Webhook) {
	o.Data = v
}

func (o WebhookList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *WebhookList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookList := _WebhookList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookList)

	if err != nil {
		return err
	}

	*o = WebhookList(varWebhookList)

	return err
}

type NullableWebhookList struct {
	value *WebhookList
	isSet bool
}

func (v NullableWebhookList) Get() *WebhookList {
	return v.value
}

func (v *NullableWebhookList) Set(val *WebhookList) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookList) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookList(val *WebhookList) *NullableWebhookList {
	return &NullableWebhookList{value: val, isSet: true}
}

func (v NullableWebhookList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


