/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
)

// checks if the Building type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Building{}

// Building struct for Building
type Building struct {
	Condition *string `json:"condition,omitempty"`
	ConstructionPhase *string `json:"construction_phase,omitempty"`
	ConstructionType *string `json:"construction_type,omitempty"`
	HeatingType *string `json:"heating_type,omitempty"`
	Leasehold *bool `json:"leasehold,omitempty"`
	MonumentProtected *bool `json:"monument_protected,omitempty"`
	YearBuilt *int32 `json:"year_built,omitempty"`
	YearRenovated *int32 `json:"year_renovated,omitempty"`
}

// NewBuilding instantiates a new Building object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuilding() *Building {
	this := Building{}
	return &this
}

// NewBuildingWithDefaults instantiates a new Building object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildingWithDefaults() *Building {
	this := Building{}
	return &this
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *Building) GetCondition() string {
	if o == nil || IsNil(o.Condition) {
		var ret string
		return ret
	}
	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetConditionOk() (*string, bool) {
	if o == nil || IsNil(o.Condition) {
		return nil, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *Building) HasCondition() bool {
	if o != nil && !IsNil(o.Condition) {
		return true
	}

	return false
}

// SetCondition gets a reference to the given string and assigns it to the Condition field.
func (o *Building) SetCondition(v string) {
	o.Condition = &v
}

// GetConstructionPhase returns the ConstructionPhase field value if set, zero value otherwise.
func (o *Building) GetConstructionPhase() string {
	if o == nil || IsNil(o.ConstructionPhase) {
		var ret string
		return ret
	}
	return *o.ConstructionPhase
}

// GetConstructionPhaseOk returns a tuple with the ConstructionPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetConstructionPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.ConstructionPhase) {
		return nil, false
	}
	return o.ConstructionPhase, true
}

// HasConstructionPhase returns a boolean if a field has been set.
func (o *Building) HasConstructionPhase() bool {
	if o != nil && !IsNil(o.ConstructionPhase) {
		return true
	}

	return false
}

// SetConstructionPhase gets a reference to the given string and assigns it to the ConstructionPhase field.
func (o *Building) SetConstructionPhase(v string) {
	o.ConstructionPhase = &v
}

// GetConstructionType returns the ConstructionType field value if set, zero value otherwise.
func (o *Building) GetConstructionType() string {
	if o == nil || IsNil(o.ConstructionType) {
		var ret string
		return ret
	}
	return *o.ConstructionType
}

// GetConstructionTypeOk returns a tuple with the ConstructionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetConstructionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ConstructionType) {
		return nil, false
	}
	return o.ConstructionType, true
}

// HasConstructionType returns a boolean if a field has been set.
func (o *Building) HasConstructionType() bool {
	if o != nil && !IsNil(o.ConstructionType) {
		return true
	}

	return false
}

// SetConstructionType gets a reference to the given string and assigns it to the ConstructionType field.
func (o *Building) SetConstructionType(v string) {
	o.ConstructionType = &v
}

// GetHeatingType returns the HeatingType field value if set, zero value otherwise.
func (o *Building) GetHeatingType() string {
	if o == nil || IsNil(o.HeatingType) {
		var ret string
		return ret
	}
	return *o.HeatingType
}

// GetHeatingTypeOk returns a tuple with the HeatingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetHeatingTypeOk() (*string, bool) {
	if o == nil || IsNil(o.HeatingType) {
		return nil, false
	}
	return o.HeatingType, true
}

// HasHeatingType returns a boolean if a field has been set.
func (o *Building) HasHeatingType() bool {
	if o != nil && !IsNil(o.HeatingType) {
		return true
	}

	return false
}

// SetHeatingType gets a reference to the given string and assigns it to the HeatingType field.
func (o *Building) SetHeatingType(v string) {
	o.HeatingType = &v
}

// GetLeasehold returns the Leasehold field value if set, zero value otherwise.
func (o *Building) GetLeasehold() bool {
	if o == nil || IsNil(o.Leasehold) {
		var ret bool
		return ret
	}
	return *o.Leasehold
}

// GetLeaseholdOk returns a tuple with the Leasehold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetLeaseholdOk() (*bool, bool) {
	if o == nil || IsNil(o.Leasehold) {
		return nil, false
	}
	return o.Leasehold, true
}

// HasLeasehold returns a boolean if a field has been set.
func (o *Building) HasLeasehold() bool {
	if o != nil && !IsNil(o.Leasehold) {
		return true
	}

	return false
}

// SetLeasehold gets a reference to the given bool and assigns it to the Leasehold field.
func (o *Building) SetLeasehold(v bool) {
	o.Leasehold = &v
}

// GetMonumentProtected returns the MonumentProtected field value if set, zero value otherwise.
func (o *Building) GetMonumentProtected() bool {
	if o == nil || IsNil(o.MonumentProtected) {
		var ret bool
		return ret
	}
	return *o.MonumentProtected
}

// GetMonumentProtectedOk returns a tuple with the MonumentProtected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetMonumentProtectedOk() (*bool, bool) {
	if o == nil || IsNil(o.MonumentProtected) {
		return nil, false
	}
	return o.MonumentProtected, true
}

// HasMonumentProtected returns a boolean if a field has been set.
func (o *Building) HasMonumentProtected() bool {
	if o != nil && !IsNil(o.MonumentProtected) {
		return true
	}

	return false
}

// SetMonumentProtected gets a reference to the given bool and assigns it to the MonumentProtected field.
func (o *Building) SetMonumentProtected(v bool) {
	o.MonumentProtected = &v
}

// GetYearBuilt returns the YearBuilt field value if set, zero value otherwise.
func (o *Building) GetYearBuilt() int32 {
	if o == nil || IsNil(o.YearBuilt) {
		var ret int32
		return ret
	}
	return *o.YearBuilt
}

// GetYearBuiltOk returns a tuple with the YearBuilt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetYearBuiltOk() (*int32, bool) {
	if o == nil || IsNil(o.YearBuilt) {
		return nil, false
	}
	return o.YearBuilt, true
}

// HasYearBuilt returns a boolean if a field has been set.
func (o *Building) HasYearBuilt() bool {
	if o != nil && !IsNil(o.YearBuilt) {
		return true
	}

	return false
}

// SetYearBuilt gets a reference to the given int32 and assigns it to the YearBuilt field.
func (o *Building) SetYearBuilt(v int32) {
	o.YearBuilt = &v
}

// GetYearRenovated returns the YearRenovated field value if set, zero value otherwise.
func (o *Building) GetYearRenovated() int32 {
	if o == nil || IsNil(o.YearRenovated) {
		var ret int32
		return ret
	}
	return *o.YearRenovated
}

// GetYearRenovatedOk returns a tuple with the YearRenovated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Building) GetYearRenovatedOk() (*int32, bool) {
	if o == nil || IsNil(o.YearRenovated) {
		return nil, false
	}
	return o.YearRenovated, true
}

// HasYearRenovated returns a boolean if a field has been set.
func (o *Building) HasYearRenovated() bool {
	if o != nil && !IsNil(o.YearRenovated) {
		return true
	}

	return false
}

// SetYearRenovated gets a reference to the given int32 and assigns it to the YearRenovated field.
func (o *Building) SetYearRenovated(v int32) {
	o.YearRenovated = &v
}

func (o Building) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Building) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Condition) {
		toSerialize["condition"] = o.Condition
	}
	if !IsNil(o.ConstructionPhase) {
		toSerialize["construction_phase"] = o.ConstructionPhase
	}
	if !IsNil(o.ConstructionType) {
		toSerialize["construction_type"] = o.ConstructionType
	}
	if !IsNil(o.HeatingType) {
		toSerialize["heating_type"] = o.HeatingType
	}
	if !IsNil(o.Leasehold) {
		toSerialize["leasehold"] = o.Leasehold
	}
	if !IsNil(o.MonumentProtected) {
		toSerialize["monument_protected"] = o.MonumentProtected
	}
	if !IsNil(o.YearBuilt) {
		toSerialize["year_built"] = o.YearBuilt
	}
	if !IsNil(o.YearRenovated) {
		toSerialize["year_renovated"] = o.YearRenovated
	}
	return toSerialize, nil
}

type NullableBuilding struct {
	value *Building
	isSet bool
}

func (v NullableBuilding) Get() *Building {
	return v.value
}

func (v *NullableBuilding) Set(val *Building) {
	v.value = val
	v.isSet = true
}

func (v NullableBuilding) IsSet() bool {
	return v.isSet
}

func (v *NullableBuilding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuilding(val *Building) *NullableBuilding {
	return &NullableBuilding{value: val, isSet: true}
}

func (v NullableBuilding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuilding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


