/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportRecord{}

// ImportRecord struct for ImportRecord
type ImportRecord struct {
	Errors []string `json:"errors,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	Location string `json:"location"`
	Outcome string `json:"outcome"`
	PropertyId *string `json:"property_id,omitempty"`
}

type _ImportRecord ImportRecord

// NewImportRecord instantiates a new ImportRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportRecord(location string, outcome string) *ImportRecord {
	this := ImportRecord{}
	this.Location = location
	this.Outcome = outcome
	return &this
}

// NewImportRecordWithDefaults instantiates a new ImportRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportRecordWithDefaults() *ImportRecord {
	this := ImportRecord{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ImportRecord) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportRecord) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ImportRecord) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *ImportRecord) SetErrors(v []string) {
	o.Errors = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *ImportRecord) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportRecord) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *ImportRecord) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *ImportRecord) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetLocation returns the Location field value
func (o *ImportRecord) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *ImportRecord) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *ImportRecord) SetLocation(v string) {
	o.Location = v
}

// GetOutcome returns the Outcome field value
func (o *ImportRecord) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *ImportRecord) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *ImportRecord) SetOutcome(v string) {
	o.Outcome = v
}

// GetPropertyId returns the PropertyId field value if set, zero value otherwise.
func (o *ImportRecord) GetPropertyId() string {
	if o == nil || IsNil(o.PropertyId) {
		var ret string
		return ret
	}
	return *o.PropertyId
}

// GetPropertyIdOk returns a tuple with the PropertyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportRecord) GetPropertyIdOk() (*string, bool) {
	if o == nil || IsNil(o.PropertyId) {
		return nil, false
	}
	return o.PropertyId, true
}

// HasPropertyId returns a boolean if a field has been set.
func (o *ImportRecord) HasPropertyId() bool {
	if o != nil && !IsNil(o.PropertyId) {
		return true
	}

	return false
}

// SetPropertyId gets a reference to the given string and assigns it to the PropertyId field.
func (o *ImportRecord) SetPropertyId(v string) {
	o.PropertyId = &v
}

func (o ImportRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	toSerialize["location"] = o.Location
	toSerialize["outcome"] = o.Outcome
	if !IsNil(o.PropertyId) {
		toSerialize["property_id"] = o.PropertyId
	}
	return toSerialize, nil
}

func (o *ImportRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"location",
		"outcome",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportRecord := _ImportRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportRecord)

	if err != nil {
		return err
	}

	*o = ImportRecord(varImportRecord)

	return err
}

type NullableImportRecord struct {
	value *ImportRecord
	isSet bool
}

func (v NullableImportRecord) Get() *ImportRecord {
	return v.value
}

func (v *NullableImportRecord) Set(val *ImportRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableImportRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableImportRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportRecord(val *ImportRecord) *NullableImportRecord {
	return &NullableImportRecord{value: val, isSet: true}
}

func (v NullableImportRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


