/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateImportSourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateImportSourceRequest{}

// CreateImportSourceRequest struct for CreateImportSourceRequest
type CreateImportSourceRequest struct {
	// explicit_only honours deletion markers alone. absence_withdraws also withdraws anything missing from a full delivery, and should only be used where the format is a complete statement of stock.
	DeletionPolicy *string `json:"deletion_policy,omitempty"`
	// How data arrives. fetch_url pulls from a URL you give us on a schedule; api_push means you send us each delivery. SFTP drops are named in the schema and are not running yet, so asking for one is refused rather than answered with credentials for a host that would never accept them.
	Delivery map[string]*interface{} `json:"delivery"`
	// Format this source delivers. Only csv and json parse today; the others are named in the schema and are refused here rather than accepted into a connector that would fail every run.
	Format string `json:"format"`
	// Field mapping, for formats that need one. Omit for OpenImmo and RESO, which are already standardised.
	Mapping map[string]*interface{} `json:"mapping,omitempty"`
	// Your own label for the connector.
	Name string `json:"name"`
	// How often to pull, for fetched sources. Cron expression in UTC. Ignored for drops and pushes, which run on arrival.
	Schedule *string `json:"schedule,omitempty"`
}

type _CreateImportSourceRequest CreateImportSourceRequest

// NewCreateImportSourceRequest instantiates a new CreateImportSourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateImportSourceRequest(delivery map[string]*interface{}, format string, name string) *CreateImportSourceRequest {
	this := CreateImportSourceRequest{}
	var deletionPolicy string = "explicit_only"
	this.DeletionPolicy = &deletionPolicy
	this.Delivery = delivery
	this.Format = format
	this.Name = name
	return &this
}

// NewCreateImportSourceRequestWithDefaults instantiates a new CreateImportSourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateImportSourceRequestWithDefaults() *CreateImportSourceRequest {
	this := CreateImportSourceRequest{}
	var deletionPolicy string = "explicit_only"
	this.DeletionPolicy = &deletionPolicy
	return &this
}

// GetDeletionPolicy returns the DeletionPolicy field value if set, zero value otherwise.
func (o *CreateImportSourceRequest) GetDeletionPolicy() string {
	if o == nil || IsNil(o.DeletionPolicy) {
		var ret string
		return ret
	}
	return *o.DeletionPolicy
}

// GetDeletionPolicyOk returns a tuple with the DeletionPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateImportSourceRequest) GetDeletionPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.DeletionPolicy) {
		return nil, false
	}
	return o.DeletionPolicy, true
}

// HasDeletionPolicy returns a boolean if a field has been set.
func (o *CreateImportSourceRequest) HasDeletionPolicy() bool {
	if o != nil && !IsNil(o.DeletionPolicy) {
		return true
	}

	return false
}

// SetDeletionPolicy gets a reference to the given string and assigns it to the DeletionPolicy field.
func (o *CreateImportSourceRequest) SetDeletionPolicy(v string) {
	o.DeletionPolicy = &v
}

// GetDelivery returns the Delivery field value
func (o *CreateImportSourceRequest) GetDelivery() map[string]*interface{} {
	if o == nil {
		var ret map[string]*interface{}
		return ret
	}

	return o.Delivery
}

// GetDeliveryOk returns a tuple with the Delivery field value
// and a boolean to check if the value has been set.
func (o *CreateImportSourceRequest) GetDeliveryOk() (map[string]*interface{}, bool) {
	if o == nil {
		return map[string]*interface{}{}, false
	}
	return o.Delivery, true
}

// SetDelivery sets field value
func (o *CreateImportSourceRequest) SetDelivery(v map[string]*interface{}) {
	o.Delivery = v
}

// GetFormat returns the Format field value
func (o *CreateImportSourceRequest) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *CreateImportSourceRequest) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *CreateImportSourceRequest) SetFormat(v string) {
	o.Format = v
}

// GetMapping returns the Mapping field value if set, zero value otherwise.
func (o *CreateImportSourceRequest) GetMapping() map[string]*interface{} {
	if o == nil || IsNil(o.Mapping) {
		var ret map[string]*interface{}
		return ret
	}
	return o.Mapping
}

// GetMappingOk returns a tuple with the Mapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateImportSourceRequest) GetMappingOk() (map[string]*interface{}, bool) {
	if o == nil || IsNil(o.Mapping) {
		return map[string]*interface{}{}, false
	}
	return o.Mapping, true
}

// HasMapping returns a boolean if a field has been set.
func (o *CreateImportSourceRequest) HasMapping() bool {
	if o != nil && !IsNil(o.Mapping) {
		return true
	}

	return false
}

// SetMapping gets a reference to the given map[string]*interface{} and assigns it to the Mapping field.
func (o *CreateImportSourceRequest) SetMapping(v map[string]*interface{}) {
	o.Mapping = v
}

// GetName returns the Name field value
func (o *CreateImportSourceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateImportSourceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateImportSourceRequest) SetName(v string) {
	o.Name = v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *CreateImportSourceRequest) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateImportSourceRequest) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *CreateImportSourceRequest) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *CreateImportSourceRequest) SetSchedule(v string) {
	o.Schedule = &v
}

func (o CreateImportSourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateImportSourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeletionPolicy) {
		toSerialize["deletion_policy"] = o.DeletionPolicy
	}
	toSerialize["delivery"] = o.Delivery
	toSerialize["format"] = o.Format
	if !IsNil(o.Mapping) {
		toSerialize["mapping"] = o.Mapping
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	return toSerialize, nil
}

func (o *CreateImportSourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"delivery",
		"format",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateImportSourceRequest := _CreateImportSourceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateImportSourceRequest)

	if err != nil {
		return err
	}

	*o = CreateImportSourceRequest(varCreateImportSourceRequest)

	return err
}

type NullableCreateImportSourceRequest struct {
	value *CreateImportSourceRequest
	isSet bool
}

func (v NullableCreateImportSourceRequest) Get() *CreateImportSourceRequest {
	return v.value
}

func (v *NullableCreateImportSourceRequest) Set(val *CreateImportSourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateImportSourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateImportSourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateImportSourceRequest(val *CreateImportSourceRequest) *NullableCreateImportSourceRequest {
	return &NullableCreateImportSourceRequest{value: val, isSet: true}
}

func (v NullableCreateImportSourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateImportSourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


