/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExportInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportInput{}

// ExportInput struct for ExportInput
type ExportInput struct {
	Fields []string `json:"fields"`
	Filters map[string]string `json:"filters"`
	Format string `json:"format"`
}

type _ExportInput ExportInput

// NewExportInput instantiates a new ExportInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportInput(fields []string, filters map[string]string, format string) *ExportInput {
	this := ExportInput{}
	this.Fields = fields
	this.Filters = filters
	this.Format = format
	return &this
}

// NewExportInputWithDefaults instantiates a new ExportInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportInputWithDefaults() *ExportInput {
	this := ExportInput{}
	return &this
}

// GetFields returns the Fields field value
func (o *ExportInput) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *ExportInput) GetFieldsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *ExportInput) SetFields(v []string) {
	o.Fields = v
}

// GetFilters returns the Filters field value
func (o *ExportInput) GetFilters() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value
// and a boolean to check if the value has been set.
func (o *ExportInput) GetFiltersOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Filters, true
}

// SetFilters sets field value
func (o *ExportInput) SetFilters(v map[string]string) {
	o.Filters = v
}

// GetFormat returns the Format field value
func (o *ExportInput) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *ExportInput) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *ExportInput) SetFormat(v string) {
	o.Format = v
}

func (o ExportInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fields"] = o.Fields
	toSerialize["filters"] = o.Filters
	toSerialize["format"] = o.Format
	return toSerialize, nil
}

func (o *ExportInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
		"filters",
		"format",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExportInput := _ExportInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExportInput)

	if err != nil {
		return err
	}

	*o = ExportInput(varExportInput)

	return err
}

type NullableExportInput struct {
	value *ExportInput
	isSet bool
}

func (v NullableExportInput) Get() *ExportInput {
	return v.value
}

func (v *NullableExportInput) Set(val *ExportInput) {
	v.value = val
	v.isSet = true
}

func (v NullableExportInput) IsSet() bool {
	return v.isSet
}

func (v *NullableExportInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportInput(val *ExportInput) *NullableExportInput {
	return &NullableExportInput{value: val, isSet: true}
}

func (v NullableExportInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


