/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GenerationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerationInput{}

// GenerationInput struct for GenerationInput
type GenerationInput struct {
	Kind string `json:"kind"`
	Prompt *string `json:"prompt,omitempty"`
	RoomType *string `json:"room_type,omitempty"`
	SourceImageId string `json:"source_image_id"`
	Style *string `json:"style,omitempty"`
}

type _GenerationInput GenerationInput

// NewGenerationInput instantiates a new GenerationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerationInput(kind string, sourceImageId string) *GenerationInput {
	this := GenerationInput{}
	this.Kind = kind
	this.SourceImageId = sourceImageId
	return &this
}

// NewGenerationInputWithDefaults instantiates a new GenerationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerationInputWithDefaults() *GenerationInput {
	this := GenerationInput{}
	return &this
}

// GetKind returns the Kind field value
func (o *GenerationInput) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *GenerationInput) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *GenerationInput) SetKind(v string) {
	o.Kind = v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *GenerationInput) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerationInput) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *GenerationInput) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *GenerationInput) SetPrompt(v string) {
	o.Prompt = &v
}

// GetRoomType returns the RoomType field value if set, zero value otherwise.
func (o *GenerationInput) GetRoomType() string {
	if o == nil || IsNil(o.RoomType) {
		var ret string
		return ret
	}
	return *o.RoomType
}

// GetRoomTypeOk returns a tuple with the RoomType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerationInput) GetRoomTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RoomType) {
		return nil, false
	}
	return o.RoomType, true
}

// HasRoomType returns a boolean if a field has been set.
func (o *GenerationInput) HasRoomType() bool {
	if o != nil && !IsNil(o.RoomType) {
		return true
	}

	return false
}

// SetRoomType gets a reference to the given string and assigns it to the RoomType field.
func (o *GenerationInput) SetRoomType(v string) {
	o.RoomType = &v
}

// GetSourceImageId returns the SourceImageId field value
func (o *GenerationInput) GetSourceImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceImageId
}

// GetSourceImageIdOk returns a tuple with the SourceImageId field value
// and a boolean to check if the value has been set.
func (o *GenerationInput) GetSourceImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceImageId, true
}

// SetSourceImageId sets field value
func (o *GenerationInput) SetSourceImageId(v string) {
	o.SourceImageId = v
}

// GetStyle returns the Style field value if set, zero value otherwise.
func (o *GenerationInput) GetStyle() string {
	if o == nil || IsNil(o.Style) {
		var ret string
		return ret
	}
	return *o.Style
}

// GetStyleOk returns a tuple with the Style field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerationInput) GetStyleOk() (*string, bool) {
	if o == nil || IsNil(o.Style) {
		return nil, false
	}
	return o.Style, true
}

// HasStyle returns a boolean if a field has been set.
func (o *GenerationInput) HasStyle() bool {
	if o != nil && !IsNil(o.Style) {
		return true
	}

	return false
}

// SetStyle gets a reference to the given string and assigns it to the Style field.
func (o *GenerationInput) SetStyle(v string) {
	o.Style = &v
}

func (o GenerationInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.RoomType) {
		toSerialize["room_type"] = o.RoomType
	}
	toSerialize["source_image_id"] = o.SourceImageId
	if !IsNil(o.Style) {
		toSerialize["style"] = o.Style
	}
	return toSerialize, nil
}

func (o *GenerationInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"source_image_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenerationInput := _GenerationInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenerationInput)

	if err != nil {
		return err
	}

	*o = GenerationInput(varGenerationInput)

	return err
}

type NullableGenerationInput struct {
	value *GenerationInput
	isSet bool
}

func (v NullableGenerationInput) Get() *GenerationInput {
	return v.value
}

func (v *NullableGenerationInput) Set(val *GenerationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerationInput(val *GenerationInput) *NullableGenerationInput {
	return &NullableGenerationInput{value: val, isSet: true}
}

func (v NullableGenerationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


