/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportResponse{}

// ExportResponse One Export.
type ExportResponse struct {
	Data Export `json:"data"`
}

type _ExportResponse ExportResponse

// NewExportResponse instantiates a new ExportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportResponse(data Export) *ExportResponse {
	this := ExportResponse{}
	this.Data = data
	return &this
}

// NewExportResponseWithDefaults instantiates a new ExportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportResponseWithDefaults() *ExportResponse {
	this := ExportResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ExportResponse) GetData() Export {
	if o == nil {
		var ret Export
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ExportResponse) GetDataOk() (*Export, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ExportResponse) SetData(v Export) {
	o.Data = v
}

func (o ExportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ExportResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExportResponse := _ExportResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExportResponse)

	if err != nil {
		return err
	}

	*o = ExportResponse(varExportResponse)

	return err
}

type NullableExportResponse struct {
	value *ExportResponse
	isSet bool
}

func (v NullableExportResponse) Get() *ExportResponse {
	return v.value
}

func (v *NullableExportResponse) Set(val *ExportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportResponse(val *ExportResponse) *NullableExportResponse {
	return &NullableExportResponse{value: val, isSet: true}
}

func (v NullableExportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


