/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InquiryStatusInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InquiryStatusInput{}

// InquiryStatusInput struct for InquiryStatusInput
type InquiryStatusInput struct {
	Status string `json:"status"`
}

type _InquiryStatusInput InquiryStatusInput

// NewInquiryStatusInput instantiates a new InquiryStatusInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInquiryStatusInput(status string) *InquiryStatusInput {
	this := InquiryStatusInput{}
	this.Status = status
	return &this
}

// NewInquiryStatusInputWithDefaults instantiates a new InquiryStatusInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInquiryStatusInputWithDefaults() *InquiryStatusInput {
	this := InquiryStatusInput{}
	return &this
}

// GetStatus returns the Status field value
func (o *InquiryStatusInput) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InquiryStatusInput) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InquiryStatusInput) SetStatus(v string) {
	o.Status = v
}

func (o InquiryStatusInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InquiryStatusInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *InquiryStatusInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInquiryStatusInput := _InquiryStatusInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInquiryStatusInput)

	if err != nil {
		return err
	}

	*o = InquiryStatusInput(varInquiryStatusInput)

	return err
}

type NullableInquiryStatusInput struct {
	value *InquiryStatusInput
	isSet bool
}

func (v NullableInquiryStatusInput) Get() *InquiryStatusInput {
	return v.value
}

func (v *NullableInquiryStatusInput) Set(val *InquiryStatusInput) {
	v.value = val
	v.isSet = true
}

func (v NullableInquiryStatusInput) IsSet() bool {
	return v.isSet
}

func (v *NullableInquiryStatusInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInquiryStatusInput(val *InquiryStatusInput) *NullableInquiryStatusInput {
	return &NullableInquiryStatusInput{value: val, isSet: true}
}

func (v NullableInquiryStatusInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInquiryStatusInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


