/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Delivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Delivery{}

// Delivery struct for Delivery
type Delivery struct {
	Attempts int32 `json:"attempts"`
	CreatedAt time.Time `json:"created_at"`
	DeliveredAt *time.Time `json:"delivered_at,omitempty"`
	Event string `json:"event"`
	Id string `json:"id"`
	MaxAttempts int32 `json:"max_attempts"`
	NextRetryAt *time.Time `json:"next_retry_at,omitempty"`
	ResponseStatus *int32 `json:"response_status,omitempty"`
	Status string `json:"status"`
}

type _Delivery Delivery

// NewDelivery instantiates a new Delivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelivery(attempts int32, createdAt time.Time, event string, id string, maxAttempts int32, status string) *Delivery {
	this := Delivery{}
	this.Attempts = attempts
	this.CreatedAt = createdAt
	this.Event = event
	this.Id = id
	this.MaxAttempts = maxAttempts
	this.Status = status
	return &this
}

// NewDeliveryWithDefaults instantiates a new Delivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryWithDefaults() *Delivery {
	this := Delivery{}
	return &this
}

// GetAttempts returns the Attempts field value
func (o *Delivery) GetAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempts
}

// GetAttemptsOk returns a tuple with the Attempts field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempts, true
}

// SetAttempts sets field value
func (o *Delivery) SetAttempts(v int32) {
	o.Attempts = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Delivery) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Delivery) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDeliveredAt returns the DeliveredAt field value if set, zero value otherwise.
func (o *Delivery) GetDeliveredAt() time.Time {
	if o == nil || IsNil(o.DeliveredAt) {
		var ret time.Time
		return ret
	}
	return *o.DeliveredAt
}

// GetDeliveredAtOk returns a tuple with the DeliveredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetDeliveredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeliveredAt) {
		return nil, false
	}
	return o.DeliveredAt, true
}

// HasDeliveredAt returns a boolean if a field has been set.
func (o *Delivery) HasDeliveredAt() bool {
	if o != nil && !IsNil(o.DeliveredAt) {
		return true
	}

	return false
}

// SetDeliveredAt gets a reference to the given time.Time and assigns it to the DeliveredAt field.
func (o *Delivery) SetDeliveredAt(v time.Time) {
	o.DeliveredAt = &v
}

// GetEvent returns the Event field value
func (o *Delivery) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *Delivery) SetEvent(v string) {
	o.Event = v
}

// GetId returns the Id field value
func (o *Delivery) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Delivery) SetId(v string) {
	o.Id = v
}

// GetMaxAttempts returns the MaxAttempts field value
func (o *Delivery) GetMaxAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxAttempts
}

// GetMaxAttemptsOk returns a tuple with the MaxAttempts field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetMaxAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAttempts, true
}

// SetMaxAttempts sets field value
func (o *Delivery) SetMaxAttempts(v int32) {
	o.MaxAttempts = v
}

// GetNextRetryAt returns the NextRetryAt field value if set, zero value otherwise.
func (o *Delivery) GetNextRetryAt() time.Time {
	if o == nil || IsNil(o.NextRetryAt) {
		var ret time.Time
		return ret
	}
	return *o.NextRetryAt
}

// GetNextRetryAtOk returns a tuple with the NextRetryAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetNextRetryAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextRetryAt) {
		return nil, false
	}
	return o.NextRetryAt, true
}

// HasNextRetryAt returns a boolean if a field has been set.
func (o *Delivery) HasNextRetryAt() bool {
	if o != nil && !IsNil(o.NextRetryAt) {
		return true
	}

	return false
}

// SetNextRetryAt gets a reference to the given time.Time and assigns it to the NextRetryAt field.
func (o *Delivery) SetNextRetryAt(v time.Time) {
	o.NextRetryAt = &v
}

// GetResponseStatus returns the ResponseStatus field value if set, zero value otherwise.
func (o *Delivery) GetResponseStatus() int32 {
	if o == nil || IsNil(o.ResponseStatus) {
		var ret int32
		return ret
	}
	return *o.ResponseStatus
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetResponseStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.ResponseStatus) {
		return nil, false
	}
	return o.ResponseStatus, true
}

// HasResponseStatus returns a boolean if a field has been set.
func (o *Delivery) HasResponseStatus() bool {
	if o != nil && !IsNil(o.ResponseStatus) {
		return true
	}

	return false
}

// SetResponseStatus gets a reference to the given int32 and assigns it to the ResponseStatus field.
func (o *Delivery) SetResponseStatus(v int32) {
	o.ResponseStatus = &v
}

// GetStatus returns the Status field value
func (o *Delivery) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Delivery) SetStatus(v string) {
	o.Status = v
}

func (o Delivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Delivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attempts"] = o.Attempts
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.DeliveredAt) {
		toSerialize["delivered_at"] = o.DeliveredAt
	}
	toSerialize["event"] = o.Event
	toSerialize["id"] = o.Id
	toSerialize["max_attempts"] = o.MaxAttempts
	if !IsNil(o.NextRetryAt) {
		toSerialize["next_retry_at"] = o.NextRetryAt
	}
	if !IsNil(o.ResponseStatus) {
		toSerialize["response_status"] = o.ResponseStatus
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *Delivery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attempts",
		"created_at",
		"event",
		"id",
		"max_attempts",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDelivery := _Delivery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDelivery)

	if err != nil {
		return err
	}

	*o = Delivery(varDelivery)

	return err
}

type NullableDelivery struct {
	value *Delivery
	isSet bool
}

func (v NullableDelivery) Get() *Delivery {
	return v.value
}

func (v *NullableDelivery) Set(val *Delivery) {
	v.value = val
	v.isSet = true
}

func (v NullableDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelivery(val *Delivery) *NullableDelivery {
	return &NullableDelivery{value: val, isSet: true}
}

func (v NullableDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


