/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeliveryList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryList{}

// DeliveryList Every Delivery record.
type DeliveryList struct {
	Data []Delivery `json:"data"`
}

type _DeliveryList DeliveryList

// NewDeliveryList instantiates a new DeliveryList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryList(data []Delivery) *DeliveryList {
	this := DeliveryList{}
	this.Data = data
	return &this
}

// NewDeliveryListWithDefaults instantiates a new DeliveryList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryListWithDefaults() *DeliveryList {
	this := DeliveryList{}
	return &this
}

// GetData returns the Data field value
func (o *DeliveryList) GetData() []Delivery {
	if o == nil {
		var ret []Delivery
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeliveryList) GetDataOk() ([]Delivery, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DeliveryList) SetData(v []Delivery) {
	o.Data = v
}

func (o DeliveryList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeliveryList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryList := _DeliveryList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryList)

	if err != nil {
		return err
	}

	*o = DeliveryList(varDeliveryList)

	return err
}

type NullableDeliveryList struct {
	value *DeliveryList
	isSet bool
}

func (v NullableDeliveryList) Get() *DeliveryList {
	return v.value
}

func (v *NullableDeliveryList) Set(val *DeliveryList) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryList) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryList(val *DeliveryList) *NullableDeliveryList {
	return &NullableDeliveryList{value: val, isSet: true}
}

func (v NullableDeliveryList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


