/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CityPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CityPage{}

// CityPage A page of City records, with the cursor for the next one.
type CityPage struct {
	Data []City `json:"data"`
	Meta *PageMeta `json:"meta,omitempty"`
}

type _CityPage CityPage

// NewCityPage instantiates a new CityPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCityPage(data []City) *CityPage {
	this := CityPage{}
	this.Data = data
	return &this
}

// NewCityPageWithDefaults instantiates a new CityPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCityPageWithDefaults() *CityPage {
	this := CityPage{}
	return &this
}

// GetData returns the Data field value
func (o *CityPage) GetData() []City {
	if o == nil {
		var ret []City
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CityPage) GetDataOk() ([]City, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CityPage) SetData(v []City) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *CityPage) GetMeta() PageMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PageMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CityPage) GetMetaOk() (*PageMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *CityPage) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PageMeta and assigns it to the Meta field.
func (o *CityPage) SetMeta(v PageMeta) {
	o.Meta = &v
}

func (o CityPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CityPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

func (o *CityPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCityPage := _CityPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCityPage)

	if err != nil {
		return err
	}

	*o = CityPage(varCityPage)

	return err
}

type NullableCityPage struct {
	value *CityPage
	isSet bool
}

func (v NullableCityPage) Get() *CityPage {
	return v.value
}

func (v *NullableCityPage) Set(val *CityPage) {
	v.value = val
	v.isSet = true
}

func (v NullableCityPage) IsSet() bool {
	return v.isSet
}

func (v *NullableCityPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCityPage(val *CityPage) *NullableCityPage {
	return &NullableCityPage{value: val, isSet: true}
}

func (v NullableCityPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCityPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


