/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SourceDelivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceDelivery{}

// SourceDelivery struct for SourceDelivery
type SourceDelivery struct {
	Type string `json:"type"`
	Url *string `json:"url,omitempty"`
	Username *string `json:"username,omitempty"`
}

type _SourceDelivery SourceDelivery

// NewSourceDelivery instantiates a new SourceDelivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceDelivery(type_ string) *SourceDelivery {
	this := SourceDelivery{}
	this.Type = type_
	return &this
}

// NewSourceDeliveryWithDefaults instantiates a new SourceDelivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceDeliveryWithDefaults() *SourceDelivery {
	this := SourceDelivery{}
	return &this
}

// GetType returns the Type field value
func (o *SourceDelivery) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SourceDelivery) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SourceDelivery) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SourceDelivery) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceDelivery) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SourceDelivery) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SourceDelivery) SetUrl(v string) {
	o.Url = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *SourceDelivery) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceDelivery) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *SourceDelivery) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *SourceDelivery) SetUsername(v string) {
	o.Username = &v
}

func (o SourceDelivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceDelivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

func (o *SourceDelivery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceDelivery := _SourceDelivery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSourceDelivery)

	if err != nil {
		return err
	}

	*o = SourceDelivery(varSourceDelivery)

	return err
}

type NullableSourceDelivery struct {
	value *SourceDelivery
	isSet bool
}

func (v NullableSourceDelivery) Get() *SourceDelivery {
	return v.value
}

func (v *NullableSourceDelivery) Set(val *SourceDelivery) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceDelivery(val *SourceDelivery) *NullableSourceDelivery {
	return &NullableSourceDelivery{value: val, isSet: true}
}

func (v NullableSourceDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


