/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Listing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Listing{}

// Listing struct for Listing
type Listing struct {
	AvailableFrom *time.Time `json:"available_from,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Deposit *float32 `json:"deposit,omitempty"`
	Price *float32 `json:"price,omitempty"`
	PricePerSqm *float32 `json:"price_per_sqm,omitempty"`
	PricePeriod *string `json:"price_period,omitempty"`
	PublishedAt *time.Time `json:"published_at,omitempty"`
	ServiceCharges *float32 `json:"service_charges,omitempty"`
	Status string `json:"status"`
	TransactionType string `json:"transaction_type"`
}

type _Listing Listing

// NewListing instantiates a new Listing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListing(status string, transactionType string) *Listing {
	this := Listing{}
	this.Status = status
	this.TransactionType = transactionType
	return &this
}

// NewListingWithDefaults instantiates a new Listing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListingWithDefaults() *Listing {
	this := Listing{}
	return &this
}

// GetAvailableFrom returns the AvailableFrom field value if set, zero value otherwise.
func (o *Listing) GetAvailableFrom() time.Time {
	if o == nil || IsNil(o.AvailableFrom) {
		var ret time.Time
		return ret
	}
	return *o.AvailableFrom
}

// GetAvailableFromOk returns a tuple with the AvailableFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetAvailableFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AvailableFrom) {
		return nil, false
	}
	return o.AvailableFrom, true
}

// HasAvailableFrom returns a boolean if a field has been set.
func (o *Listing) HasAvailableFrom() bool {
	if o != nil && !IsNil(o.AvailableFrom) {
		return true
	}

	return false
}

// SetAvailableFrom gets a reference to the given time.Time and assigns it to the AvailableFrom field.
func (o *Listing) SetAvailableFrom(v time.Time) {
	o.AvailableFrom = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Listing) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Listing) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Listing) SetCurrency(v string) {
	o.Currency = &v
}

// GetDeposit returns the Deposit field value if set, zero value otherwise.
func (o *Listing) GetDeposit() float32 {
	if o == nil || IsNil(o.Deposit) {
		var ret float32
		return ret
	}
	return *o.Deposit
}

// GetDepositOk returns a tuple with the Deposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetDepositOk() (*float32, bool) {
	if o == nil || IsNil(o.Deposit) {
		return nil, false
	}
	return o.Deposit, true
}

// HasDeposit returns a boolean if a field has been set.
func (o *Listing) HasDeposit() bool {
	if o != nil && !IsNil(o.Deposit) {
		return true
	}

	return false
}

// SetDeposit gets a reference to the given float32 and assigns it to the Deposit field.
func (o *Listing) SetDeposit(v float32) {
	o.Deposit = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *Listing) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *Listing) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *Listing) SetPrice(v float32) {
	o.Price = &v
}

// GetPricePerSqm returns the PricePerSqm field value if set, zero value otherwise.
func (o *Listing) GetPricePerSqm() float32 {
	if o == nil || IsNil(o.PricePerSqm) {
		var ret float32
		return ret
	}
	return *o.PricePerSqm
}

// GetPricePerSqmOk returns a tuple with the PricePerSqm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetPricePerSqmOk() (*float32, bool) {
	if o == nil || IsNil(o.PricePerSqm) {
		return nil, false
	}
	return o.PricePerSqm, true
}

// HasPricePerSqm returns a boolean if a field has been set.
func (o *Listing) HasPricePerSqm() bool {
	if o != nil && !IsNil(o.PricePerSqm) {
		return true
	}

	return false
}

// SetPricePerSqm gets a reference to the given float32 and assigns it to the PricePerSqm field.
func (o *Listing) SetPricePerSqm(v float32) {
	o.PricePerSqm = &v
}

// GetPricePeriod returns the PricePeriod field value if set, zero value otherwise.
func (o *Listing) GetPricePeriod() string {
	if o == nil || IsNil(o.PricePeriod) {
		var ret string
		return ret
	}
	return *o.PricePeriod
}

// GetPricePeriodOk returns a tuple with the PricePeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetPricePeriodOk() (*string, bool) {
	if o == nil || IsNil(o.PricePeriod) {
		return nil, false
	}
	return o.PricePeriod, true
}

// HasPricePeriod returns a boolean if a field has been set.
func (o *Listing) HasPricePeriod() bool {
	if o != nil && !IsNil(o.PricePeriod) {
		return true
	}

	return false
}

// SetPricePeriod gets a reference to the given string and assigns it to the PricePeriod field.
func (o *Listing) SetPricePeriod(v string) {
	o.PricePeriod = &v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise.
func (o *Listing) GetPublishedAt() time.Time {
	if o == nil || IsNil(o.PublishedAt) {
		var ret time.Time
		return ret
	}
	return *o.PublishedAt
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetPublishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PublishedAt) {
		return nil, false
	}
	return o.PublishedAt, true
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *Listing) HasPublishedAt() bool {
	if o != nil && !IsNil(o.PublishedAt) {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given time.Time and assigns it to the PublishedAt field.
func (o *Listing) SetPublishedAt(v time.Time) {
	o.PublishedAt = &v
}

// GetServiceCharges returns the ServiceCharges field value if set, zero value otherwise.
func (o *Listing) GetServiceCharges() float32 {
	if o == nil || IsNil(o.ServiceCharges) {
		var ret float32
		return ret
	}
	return *o.ServiceCharges
}

// GetServiceChargesOk returns a tuple with the ServiceCharges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Listing) GetServiceChargesOk() (*float32, bool) {
	if o == nil || IsNil(o.ServiceCharges) {
		return nil, false
	}
	return o.ServiceCharges, true
}

// HasServiceCharges returns a boolean if a field has been set.
func (o *Listing) HasServiceCharges() bool {
	if o != nil && !IsNil(o.ServiceCharges) {
		return true
	}

	return false
}

// SetServiceCharges gets a reference to the given float32 and assigns it to the ServiceCharges field.
func (o *Listing) SetServiceCharges(v float32) {
	o.ServiceCharges = &v
}

// GetStatus returns the Status field value
func (o *Listing) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Listing) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Listing) SetStatus(v string) {
	o.Status = v
}

// GetTransactionType returns the TransactionType field value
func (o *Listing) GetTransactionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value
// and a boolean to check if the value has been set.
func (o *Listing) GetTransactionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionType, true
}

// SetTransactionType sets field value
func (o *Listing) SetTransactionType(v string) {
	o.TransactionType = v
}

func (o Listing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Listing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailableFrom) {
		toSerialize["available_from"] = o.AvailableFrom
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Deposit) {
		toSerialize["deposit"] = o.Deposit
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.PricePerSqm) {
		toSerialize["price_per_sqm"] = o.PricePerSqm
	}
	if !IsNil(o.PricePeriod) {
		toSerialize["price_period"] = o.PricePeriod
	}
	if !IsNil(o.PublishedAt) {
		toSerialize["published_at"] = o.PublishedAt
	}
	if !IsNil(o.ServiceCharges) {
		toSerialize["service_charges"] = o.ServiceCharges
	}
	toSerialize["status"] = o.Status
	toSerialize["transaction_type"] = o.TransactionType
	return toSerialize, nil
}

func (o *Listing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"transaction_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListing := _Listing{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListing)

	if err != nil {
		return err
	}

	*o = Listing(varListing)

	return err
}

type NullableListing struct {
	value *Listing
	isSet bool
}

func (v NullableListing) Get() *Listing {
	return v.value
}

func (v *NullableListing) Set(val *Listing) {
	v.value = val
	v.isSet = true
}

func (v NullableListing) IsSet() bool {
	return v.isSet
}

func (v *NullableListing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListing(val *Listing) *NullableListing {
	return &NullableListing{value: val, isSet: true}
}

func (v NullableListing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


