/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
)

// checks if the Descriptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Descriptions{}

// Descriptions struct for Descriptions
type Descriptions struct {
	Fittings *string `json:"fittings,omitempty"`
	Location *string `json:"location,omitempty"`
	Other *string `json:"other,omitempty"`
}

// NewDescriptions instantiates a new Descriptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescriptions() *Descriptions {
	this := Descriptions{}
	return &this
}

// NewDescriptionsWithDefaults instantiates a new Descriptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescriptionsWithDefaults() *Descriptions {
	this := Descriptions{}
	return &this
}

// GetFittings returns the Fittings field value if set, zero value otherwise.
func (o *Descriptions) GetFittings() string {
	if o == nil || IsNil(o.Fittings) {
		var ret string
		return ret
	}
	return *o.Fittings
}

// GetFittingsOk returns a tuple with the Fittings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Descriptions) GetFittingsOk() (*string, bool) {
	if o == nil || IsNil(o.Fittings) {
		return nil, false
	}
	return o.Fittings, true
}

// HasFittings returns a boolean if a field has been set.
func (o *Descriptions) HasFittings() bool {
	if o != nil && !IsNil(o.Fittings) {
		return true
	}

	return false
}

// SetFittings gets a reference to the given string and assigns it to the Fittings field.
func (o *Descriptions) SetFittings(v string) {
	o.Fittings = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Descriptions) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Descriptions) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Descriptions) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *Descriptions) SetLocation(v string) {
	o.Location = &v
}

// GetOther returns the Other field value if set, zero value otherwise.
func (o *Descriptions) GetOther() string {
	if o == nil || IsNil(o.Other) {
		var ret string
		return ret
	}
	return *o.Other
}

// GetOtherOk returns a tuple with the Other field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Descriptions) GetOtherOk() (*string, bool) {
	if o == nil || IsNil(o.Other) {
		return nil, false
	}
	return o.Other, true
}

// HasOther returns a boolean if a field has been set.
func (o *Descriptions) HasOther() bool {
	if o != nil && !IsNil(o.Other) {
		return true
	}

	return false
}

// SetOther gets a reference to the given string and assigns it to the Other field.
func (o *Descriptions) SetOther(v string) {
	o.Other = &v
}

func (o Descriptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Descriptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fittings) {
		toSerialize["fittings"] = o.Fittings
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Other) {
		toSerialize["other"] = o.Other
	}
	return toSerialize, nil
}

type NullableDescriptions struct {
	value *Descriptions
	isSet bool
}

func (v NullableDescriptions) Get() *Descriptions {
	return v.value
}

func (v *NullableDescriptions) Set(val *Descriptions) {
	v.value = val
	v.isSet = true
}

func (v NullableDescriptions) IsSet() bool {
	return v.isSet
}

func (v *NullableDescriptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescriptions(val *Descriptions) *NullableDescriptions {
	return &NullableDescriptions{value: val, isSet: true}
}

func (v NullableDescriptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescriptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


