/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PriceObservation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceObservation{}

// PriceObservation struct for PriceObservation
type PriceObservation struct {
	Currency string `json:"currency"`
	ObservedAt time.Time `json:"observed_at"`
	Price *float32 `json:"price,omitempty"`
	Source *string `json:"source,omitempty"`
}

type _PriceObservation PriceObservation

// NewPriceObservation instantiates a new PriceObservation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceObservation(currency string, observedAt time.Time) *PriceObservation {
	this := PriceObservation{}
	this.Currency = currency
	this.ObservedAt = observedAt
	return &this
}

// NewPriceObservationWithDefaults instantiates a new PriceObservation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceObservationWithDefaults() *PriceObservation {
	this := PriceObservation{}
	return &this
}

// GetCurrency returns the Currency field value
func (o *PriceObservation) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PriceObservation) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PriceObservation) SetCurrency(v string) {
	o.Currency = v
}

// GetObservedAt returns the ObservedAt field value
func (o *PriceObservation) GetObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
func (o *PriceObservation) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAt, true
}

// SetObservedAt sets field value
func (o *PriceObservation) SetObservedAt(v time.Time) {
	o.ObservedAt = v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *PriceObservation) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceObservation) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *PriceObservation) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *PriceObservation) SetPrice(v float32) {
	o.Price = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *PriceObservation) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceObservation) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *PriceObservation) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *PriceObservation) SetSource(v string) {
	o.Source = &v
}

func (o PriceObservation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceObservation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	toSerialize["observed_at"] = o.ObservedAt
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

func (o *PriceObservation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currency",
		"observed_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPriceObservation := _PriceObservation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPriceObservation)

	if err != nil {
		return err
	}

	*o = PriceObservation(varPriceObservation)

	return err
}

type NullablePriceObservation struct {
	value *PriceObservation
	isSet bool
}

func (v NullablePriceObservation) Get() *PriceObservation {
	return v.value
}

func (v *NullablePriceObservation) Set(val *PriceObservation) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceObservation) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceObservation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceObservation(val *PriceObservation) *NullablePriceObservation {
	return &NullablePriceObservation{value: val, isSet: true}
}

func (v NullablePriceObservation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceObservation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


