/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
)

// checks if the Features type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Features{}

// Features struct for Features
type Features struct {
	AirConditioning *bool `json:"air_conditioning,omitempty"`
	AlarmSystem *bool `json:"alarm_system,omitempty"`
	Balcony *bool `json:"balcony,omitempty"`
	BarrierFree *bool `json:"barrier_free,omitempty"`
	Cellar *bool `json:"cellar,omitempty"`
	Fireplace *bool `json:"fireplace,omitempty"`
	FittedKitchen *bool `json:"fitted_kitchen,omitempty"`
	Flooring *string `json:"flooring,omitempty"`
	Furnished *bool `json:"furnished,omitempty"`
	Garden *bool `json:"garden,omitempty"`
	GuestToilet *bool `json:"guest_toilet,omitempty"`
	KitchenType *string `json:"kitchen_type,omitempty"`
	Lift *bool `json:"lift,omitempty"`
	Pool *bool `json:"pool,omitempty"`
	Sauna *bool `json:"sauna,omitempty"`
	SolarPanels *bool `json:"solar_panels,omitempty"`
	Terrace *bool `json:"terrace,omitempty"`
	WindowGlazing *string `json:"window_glazing,omitempty"`
}

// NewFeatures instantiates a new Features object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatures() *Features {
	this := Features{}
	return &this
}

// NewFeaturesWithDefaults instantiates a new Features object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeaturesWithDefaults() *Features {
	this := Features{}
	return &this
}

// GetAirConditioning returns the AirConditioning field value if set, zero value otherwise.
func (o *Features) GetAirConditioning() bool {
	if o == nil || IsNil(o.AirConditioning) {
		var ret bool
		return ret
	}
	return *o.AirConditioning
}

// GetAirConditioningOk returns a tuple with the AirConditioning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetAirConditioningOk() (*bool, bool) {
	if o == nil || IsNil(o.AirConditioning) {
		return nil, false
	}
	return o.AirConditioning, true
}

// HasAirConditioning returns a boolean if a field has been set.
func (o *Features) HasAirConditioning() bool {
	if o != nil && !IsNil(o.AirConditioning) {
		return true
	}

	return false
}

// SetAirConditioning gets a reference to the given bool and assigns it to the AirConditioning field.
func (o *Features) SetAirConditioning(v bool) {
	o.AirConditioning = &v
}

// GetAlarmSystem returns the AlarmSystem field value if set, zero value otherwise.
func (o *Features) GetAlarmSystem() bool {
	if o == nil || IsNil(o.AlarmSystem) {
		var ret bool
		return ret
	}
	return *o.AlarmSystem
}

// GetAlarmSystemOk returns a tuple with the AlarmSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetAlarmSystemOk() (*bool, bool) {
	if o == nil || IsNil(o.AlarmSystem) {
		return nil, false
	}
	return o.AlarmSystem, true
}

// HasAlarmSystem returns a boolean if a field has been set.
func (o *Features) HasAlarmSystem() bool {
	if o != nil && !IsNil(o.AlarmSystem) {
		return true
	}

	return false
}

// SetAlarmSystem gets a reference to the given bool and assigns it to the AlarmSystem field.
func (o *Features) SetAlarmSystem(v bool) {
	o.AlarmSystem = &v
}

// GetBalcony returns the Balcony field value if set, zero value otherwise.
func (o *Features) GetBalcony() bool {
	if o == nil || IsNil(o.Balcony) {
		var ret bool
		return ret
	}
	return *o.Balcony
}

// GetBalconyOk returns a tuple with the Balcony field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetBalconyOk() (*bool, bool) {
	if o == nil || IsNil(o.Balcony) {
		return nil, false
	}
	return o.Balcony, true
}

// HasBalcony returns a boolean if a field has been set.
func (o *Features) HasBalcony() bool {
	if o != nil && !IsNil(o.Balcony) {
		return true
	}

	return false
}

// SetBalcony gets a reference to the given bool and assigns it to the Balcony field.
func (o *Features) SetBalcony(v bool) {
	o.Balcony = &v
}

// GetBarrierFree returns the BarrierFree field value if set, zero value otherwise.
func (o *Features) GetBarrierFree() bool {
	if o == nil || IsNil(o.BarrierFree) {
		var ret bool
		return ret
	}
	return *o.BarrierFree
}

// GetBarrierFreeOk returns a tuple with the BarrierFree field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetBarrierFreeOk() (*bool, bool) {
	if o == nil || IsNil(o.BarrierFree) {
		return nil, false
	}
	return o.BarrierFree, true
}

// HasBarrierFree returns a boolean if a field has been set.
func (o *Features) HasBarrierFree() bool {
	if o != nil && !IsNil(o.BarrierFree) {
		return true
	}

	return false
}

// SetBarrierFree gets a reference to the given bool and assigns it to the BarrierFree field.
func (o *Features) SetBarrierFree(v bool) {
	o.BarrierFree = &v
}

// GetCellar returns the Cellar field value if set, zero value otherwise.
func (o *Features) GetCellar() bool {
	if o == nil || IsNil(o.Cellar) {
		var ret bool
		return ret
	}
	return *o.Cellar
}

// GetCellarOk returns a tuple with the Cellar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetCellarOk() (*bool, bool) {
	if o == nil || IsNil(o.Cellar) {
		return nil, false
	}
	return o.Cellar, true
}

// HasCellar returns a boolean if a field has been set.
func (o *Features) HasCellar() bool {
	if o != nil && !IsNil(o.Cellar) {
		return true
	}

	return false
}

// SetCellar gets a reference to the given bool and assigns it to the Cellar field.
func (o *Features) SetCellar(v bool) {
	o.Cellar = &v
}

// GetFireplace returns the Fireplace field value if set, zero value otherwise.
func (o *Features) GetFireplace() bool {
	if o == nil || IsNil(o.Fireplace) {
		var ret bool
		return ret
	}
	return *o.Fireplace
}

// GetFireplaceOk returns a tuple with the Fireplace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetFireplaceOk() (*bool, bool) {
	if o == nil || IsNil(o.Fireplace) {
		return nil, false
	}
	return o.Fireplace, true
}

// HasFireplace returns a boolean if a field has been set.
func (o *Features) HasFireplace() bool {
	if o != nil && !IsNil(o.Fireplace) {
		return true
	}

	return false
}

// SetFireplace gets a reference to the given bool and assigns it to the Fireplace field.
func (o *Features) SetFireplace(v bool) {
	o.Fireplace = &v
}

// GetFittedKitchen returns the FittedKitchen field value if set, zero value otherwise.
func (o *Features) GetFittedKitchen() bool {
	if o == nil || IsNil(o.FittedKitchen) {
		var ret bool
		return ret
	}
	return *o.FittedKitchen
}

// GetFittedKitchenOk returns a tuple with the FittedKitchen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetFittedKitchenOk() (*bool, bool) {
	if o == nil || IsNil(o.FittedKitchen) {
		return nil, false
	}
	return o.FittedKitchen, true
}

// HasFittedKitchen returns a boolean if a field has been set.
func (o *Features) HasFittedKitchen() bool {
	if o != nil && !IsNil(o.FittedKitchen) {
		return true
	}

	return false
}

// SetFittedKitchen gets a reference to the given bool and assigns it to the FittedKitchen field.
func (o *Features) SetFittedKitchen(v bool) {
	o.FittedKitchen = &v
}

// GetFlooring returns the Flooring field value if set, zero value otherwise.
func (o *Features) GetFlooring() string {
	if o == nil || IsNil(o.Flooring) {
		var ret string
		return ret
	}
	return *o.Flooring
}

// GetFlooringOk returns a tuple with the Flooring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetFlooringOk() (*string, bool) {
	if o == nil || IsNil(o.Flooring) {
		return nil, false
	}
	return o.Flooring, true
}

// HasFlooring returns a boolean if a field has been set.
func (o *Features) HasFlooring() bool {
	if o != nil && !IsNil(o.Flooring) {
		return true
	}

	return false
}

// SetFlooring gets a reference to the given string and assigns it to the Flooring field.
func (o *Features) SetFlooring(v string) {
	o.Flooring = &v
}

// GetFurnished returns the Furnished field value if set, zero value otherwise.
func (o *Features) GetFurnished() bool {
	if o == nil || IsNil(o.Furnished) {
		var ret bool
		return ret
	}
	return *o.Furnished
}

// GetFurnishedOk returns a tuple with the Furnished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetFurnishedOk() (*bool, bool) {
	if o == nil || IsNil(o.Furnished) {
		return nil, false
	}
	return o.Furnished, true
}

// HasFurnished returns a boolean if a field has been set.
func (o *Features) HasFurnished() bool {
	if o != nil && !IsNil(o.Furnished) {
		return true
	}

	return false
}

// SetFurnished gets a reference to the given bool and assigns it to the Furnished field.
func (o *Features) SetFurnished(v bool) {
	o.Furnished = &v
}

// GetGarden returns the Garden field value if set, zero value otherwise.
func (o *Features) GetGarden() bool {
	if o == nil || IsNil(o.Garden) {
		var ret bool
		return ret
	}
	return *o.Garden
}

// GetGardenOk returns a tuple with the Garden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetGardenOk() (*bool, bool) {
	if o == nil || IsNil(o.Garden) {
		return nil, false
	}
	return o.Garden, true
}

// HasGarden returns a boolean if a field has been set.
func (o *Features) HasGarden() bool {
	if o != nil && !IsNil(o.Garden) {
		return true
	}

	return false
}

// SetGarden gets a reference to the given bool and assigns it to the Garden field.
func (o *Features) SetGarden(v bool) {
	o.Garden = &v
}

// GetGuestToilet returns the GuestToilet field value if set, zero value otherwise.
func (o *Features) GetGuestToilet() bool {
	if o == nil || IsNil(o.GuestToilet) {
		var ret bool
		return ret
	}
	return *o.GuestToilet
}

// GetGuestToiletOk returns a tuple with the GuestToilet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetGuestToiletOk() (*bool, bool) {
	if o == nil || IsNil(o.GuestToilet) {
		return nil, false
	}
	return o.GuestToilet, true
}

// HasGuestToilet returns a boolean if a field has been set.
func (o *Features) HasGuestToilet() bool {
	if o != nil && !IsNil(o.GuestToilet) {
		return true
	}

	return false
}

// SetGuestToilet gets a reference to the given bool and assigns it to the GuestToilet field.
func (o *Features) SetGuestToilet(v bool) {
	o.GuestToilet = &v
}

// GetKitchenType returns the KitchenType field value if set, zero value otherwise.
func (o *Features) GetKitchenType() string {
	if o == nil || IsNil(o.KitchenType) {
		var ret string
		return ret
	}
	return *o.KitchenType
}

// GetKitchenTypeOk returns a tuple with the KitchenType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetKitchenTypeOk() (*string, bool) {
	if o == nil || IsNil(o.KitchenType) {
		return nil, false
	}
	return o.KitchenType, true
}

// HasKitchenType returns a boolean if a field has been set.
func (o *Features) HasKitchenType() bool {
	if o != nil && !IsNil(o.KitchenType) {
		return true
	}

	return false
}

// SetKitchenType gets a reference to the given string and assigns it to the KitchenType field.
func (o *Features) SetKitchenType(v string) {
	o.KitchenType = &v
}

// GetLift returns the Lift field value if set, zero value otherwise.
func (o *Features) GetLift() bool {
	if o == nil || IsNil(o.Lift) {
		var ret bool
		return ret
	}
	return *o.Lift
}

// GetLiftOk returns a tuple with the Lift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetLiftOk() (*bool, bool) {
	if o == nil || IsNil(o.Lift) {
		return nil, false
	}
	return o.Lift, true
}

// HasLift returns a boolean if a field has been set.
func (o *Features) HasLift() bool {
	if o != nil && !IsNil(o.Lift) {
		return true
	}

	return false
}

// SetLift gets a reference to the given bool and assigns it to the Lift field.
func (o *Features) SetLift(v bool) {
	o.Lift = &v
}

// GetPool returns the Pool field value if set, zero value otherwise.
func (o *Features) GetPool() bool {
	if o == nil || IsNil(o.Pool) {
		var ret bool
		return ret
	}
	return *o.Pool
}

// GetPoolOk returns a tuple with the Pool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetPoolOk() (*bool, bool) {
	if o == nil || IsNil(o.Pool) {
		return nil, false
	}
	return o.Pool, true
}

// HasPool returns a boolean if a field has been set.
func (o *Features) HasPool() bool {
	if o != nil && !IsNil(o.Pool) {
		return true
	}

	return false
}

// SetPool gets a reference to the given bool and assigns it to the Pool field.
func (o *Features) SetPool(v bool) {
	o.Pool = &v
}

// GetSauna returns the Sauna field value if set, zero value otherwise.
func (o *Features) GetSauna() bool {
	if o == nil || IsNil(o.Sauna) {
		var ret bool
		return ret
	}
	return *o.Sauna
}

// GetSaunaOk returns a tuple with the Sauna field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetSaunaOk() (*bool, bool) {
	if o == nil || IsNil(o.Sauna) {
		return nil, false
	}
	return o.Sauna, true
}

// HasSauna returns a boolean if a field has been set.
func (o *Features) HasSauna() bool {
	if o != nil && !IsNil(o.Sauna) {
		return true
	}

	return false
}

// SetSauna gets a reference to the given bool and assigns it to the Sauna field.
func (o *Features) SetSauna(v bool) {
	o.Sauna = &v
}

// GetSolarPanels returns the SolarPanels field value if set, zero value otherwise.
func (o *Features) GetSolarPanels() bool {
	if o == nil || IsNil(o.SolarPanels) {
		var ret bool
		return ret
	}
	return *o.SolarPanels
}

// GetSolarPanelsOk returns a tuple with the SolarPanels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetSolarPanelsOk() (*bool, bool) {
	if o == nil || IsNil(o.SolarPanels) {
		return nil, false
	}
	return o.SolarPanels, true
}

// HasSolarPanels returns a boolean if a field has been set.
func (o *Features) HasSolarPanels() bool {
	if o != nil && !IsNil(o.SolarPanels) {
		return true
	}

	return false
}

// SetSolarPanels gets a reference to the given bool and assigns it to the SolarPanels field.
func (o *Features) SetSolarPanels(v bool) {
	o.SolarPanels = &v
}

// GetTerrace returns the Terrace field value if set, zero value otherwise.
func (o *Features) GetTerrace() bool {
	if o == nil || IsNil(o.Terrace) {
		var ret bool
		return ret
	}
	return *o.Terrace
}

// GetTerraceOk returns a tuple with the Terrace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetTerraceOk() (*bool, bool) {
	if o == nil || IsNil(o.Terrace) {
		return nil, false
	}
	return o.Terrace, true
}

// HasTerrace returns a boolean if a field has been set.
func (o *Features) HasTerrace() bool {
	if o != nil && !IsNil(o.Terrace) {
		return true
	}

	return false
}

// SetTerrace gets a reference to the given bool and assigns it to the Terrace field.
func (o *Features) SetTerrace(v bool) {
	o.Terrace = &v
}

// GetWindowGlazing returns the WindowGlazing field value if set, zero value otherwise.
func (o *Features) GetWindowGlazing() string {
	if o == nil || IsNil(o.WindowGlazing) {
		var ret string
		return ret
	}
	return *o.WindowGlazing
}

// GetWindowGlazingOk returns a tuple with the WindowGlazing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Features) GetWindowGlazingOk() (*string, bool) {
	if o == nil || IsNil(o.WindowGlazing) {
		return nil, false
	}
	return o.WindowGlazing, true
}

// HasWindowGlazing returns a boolean if a field has been set.
func (o *Features) HasWindowGlazing() bool {
	if o != nil && !IsNil(o.WindowGlazing) {
		return true
	}

	return false
}

// SetWindowGlazing gets a reference to the given string and assigns it to the WindowGlazing field.
func (o *Features) SetWindowGlazing(v string) {
	o.WindowGlazing = &v
}

func (o Features) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Features) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AirConditioning) {
		toSerialize["air_conditioning"] = o.AirConditioning
	}
	if !IsNil(o.AlarmSystem) {
		toSerialize["alarm_system"] = o.AlarmSystem
	}
	if !IsNil(o.Balcony) {
		toSerialize["balcony"] = o.Balcony
	}
	if !IsNil(o.BarrierFree) {
		toSerialize["barrier_free"] = o.BarrierFree
	}
	if !IsNil(o.Cellar) {
		toSerialize["cellar"] = o.Cellar
	}
	if !IsNil(o.Fireplace) {
		toSerialize["fireplace"] = o.Fireplace
	}
	if !IsNil(o.FittedKitchen) {
		toSerialize["fitted_kitchen"] = o.FittedKitchen
	}
	if !IsNil(o.Flooring) {
		toSerialize["flooring"] = o.Flooring
	}
	if !IsNil(o.Furnished) {
		toSerialize["furnished"] = o.Furnished
	}
	if !IsNil(o.Garden) {
		toSerialize["garden"] = o.Garden
	}
	if !IsNil(o.GuestToilet) {
		toSerialize["guest_toilet"] = o.GuestToilet
	}
	if !IsNil(o.KitchenType) {
		toSerialize["kitchen_type"] = o.KitchenType
	}
	if !IsNil(o.Lift) {
		toSerialize["lift"] = o.Lift
	}
	if !IsNil(o.Pool) {
		toSerialize["pool"] = o.Pool
	}
	if !IsNil(o.Sauna) {
		toSerialize["sauna"] = o.Sauna
	}
	if !IsNil(o.SolarPanels) {
		toSerialize["solar_panels"] = o.SolarPanels
	}
	if !IsNil(o.Terrace) {
		toSerialize["terrace"] = o.Terrace
	}
	if !IsNil(o.WindowGlazing) {
		toSerialize["window_glazing"] = o.WindowGlazing
	}
	return toSerialize, nil
}

type NullableFeatures struct {
	value *Features
	isSet bool
}

func (v NullableFeatures) Get() *Features {
	return v.value
}

func (v *NullableFeatures) Set(val *Features) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatures) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatures(val *Features) *NullableFeatures {
	return &NullableFeatures{value: val, isSet: true}
}

func (v NullableFeatures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


