/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InquiryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InquiryResponse{}

// InquiryResponse One Inquiry.
type InquiryResponse struct {
	Data Inquiry `json:"data"`
}

type _InquiryResponse InquiryResponse

// NewInquiryResponse instantiates a new InquiryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInquiryResponse(data Inquiry) *InquiryResponse {
	this := InquiryResponse{}
	this.Data = data
	return &this
}

// NewInquiryResponseWithDefaults instantiates a new InquiryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInquiryResponseWithDefaults() *InquiryResponse {
	this := InquiryResponse{}
	return &this
}

// GetData returns the Data field value
func (o *InquiryResponse) GetData() Inquiry {
	if o == nil {
		var ret Inquiry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InquiryResponse) GetDataOk() (*Inquiry, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *InquiryResponse) SetData(v Inquiry) {
	o.Data = v
}

func (o InquiryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InquiryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *InquiryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInquiryResponse := _InquiryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInquiryResponse)

	if err != nil {
		return err
	}

	*o = InquiryResponse(varInquiryResponse)

	return err
}

type NullableInquiryResponse struct {
	value *InquiryResponse
	isSet bool
}

func (v NullableInquiryResponse) Get() *InquiryResponse {
	return v.value
}

func (v *NullableInquiryResponse) Set(val *InquiryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInquiryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInquiryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInquiryResponse(val *InquiryResponse) *NullableInquiryResponse {
	return &NullableInquiryResponse{value: val, isSet: true}
}

func (v NullableInquiryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInquiryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


