/*
Skautik Partner API

The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skautik

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportSourceInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportSourceInput{}

// ImportSourceInput struct for ImportSourceInput
type ImportSourceInput struct {
	DeletionPolicy string `json:"deletion_policy"`
	Delivery DeliveryInput `json:"delivery"`
	Format string `json:"format"`
	Mapping map[string]string `json:"mapping"`
	Name string `json:"name"`
	Schedule string `json:"schedule"`
}

type _ImportSourceInput ImportSourceInput

// NewImportSourceInput instantiates a new ImportSourceInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportSourceInput(deletionPolicy string, delivery DeliveryInput, format string, mapping map[string]string, name string, schedule string) *ImportSourceInput {
	this := ImportSourceInput{}
	this.DeletionPolicy = deletionPolicy
	this.Delivery = delivery
	this.Format = format
	this.Mapping = mapping
	this.Name = name
	this.Schedule = schedule
	return &this
}

// NewImportSourceInputWithDefaults instantiates a new ImportSourceInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportSourceInputWithDefaults() *ImportSourceInput {
	this := ImportSourceInput{}
	return &this
}

// GetDeletionPolicy returns the DeletionPolicy field value
func (o *ImportSourceInput) GetDeletionPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeletionPolicy
}

// GetDeletionPolicyOk returns a tuple with the DeletionPolicy field value
// and a boolean to check if the value has been set.
func (o *ImportSourceInput) GetDeletionPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletionPolicy, true
}

// SetDeletionPolicy sets field value
func (o *ImportSourceInput) SetDeletionPolicy(v string) {
	o.DeletionPolicy = v
}

// GetDelivery returns the Delivery field value
func (o *ImportSourceInput) GetDelivery() DeliveryInput {
	if o == nil {
		var ret DeliveryInput
		return ret
	}

	return o.Delivery
}

// GetDeliveryOk returns a tuple with the Delivery field value
// and a boolean to check if the value has been set.
func (o *ImportSourceInput) GetDeliveryOk() (*DeliveryInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delivery, true
}

// SetDelivery sets field value
func (o *ImportSourceInput) SetDelivery(v DeliveryInput) {
	o.Delivery = v
}

// GetFormat returns the Format field value
func (o *ImportSourceInput) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *ImportSourceInput) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *ImportSourceInput) SetFormat(v string) {
	o.Format = v
}

// GetMapping returns the Mapping field value
func (o *ImportSourceInput) GetMapping() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Mapping
}

// GetMappingOk returns a tuple with the Mapping field value
// and a boolean to check if the value has been set.
func (o *ImportSourceInput) GetMappingOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Mapping, true
}

// SetMapping sets field value
func (o *ImportSourceInput) SetMapping(v map[string]string) {
	o.Mapping = v
}

// GetName returns the Name field value
func (o *ImportSourceInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ImportSourceInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ImportSourceInput) SetName(v string) {
	o.Name = v
}

// GetSchedule returns the Schedule field value
func (o *ImportSourceInput) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *ImportSourceInput) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *ImportSourceInput) SetSchedule(v string) {
	o.Schedule = v
}

func (o ImportSourceInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportSourceInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deletion_policy"] = o.DeletionPolicy
	toSerialize["delivery"] = o.Delivery
	toSerialize["format"] = o.Format
	toSerialize["mapping"] = o.Mapping
	toSerialize["name"] = o.Name
	toSerialize["schedule"] = o.Schedule
	return toSerialize, nil
}

func (o *ImportSourceInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deletion_policy",
		"delivery",
		"format",
		"mapping",
		"name",
		"schedule",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportSourceInput := _ImportSourceInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportSourceInput)

	if err != nil {
		return err
	}

	*o = ImportSourceInput(varImportSourceInput)

	return err
}

type NullableImportSourceInput struct {
	value *ImportSourceInput
	isSet bool
}

func (v NullableImportSourceInput) Get() *ImportSourceInput {
	return v.value
}

func (v *NullableImportSourceInput) Set(val *ImportSourceInput) {
	v.value = val
	v.isSet = true
}

func (v NullableImportSourceInput) IsSet() bool {
	return v.isSet
}

func (v *NullableImportSourceInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportSourceInput(val *ImportSourceInput) *NullableImportSourceInput {
	return &NullableImportSourceInput{value: val, isSet: true}
}

func (v NullableImportSourceInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportSourceInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


