// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package skautik

import "iter"

// AllInquiries yields every record, following the cursor.
//
// The same request as ListInquiries, with the paging done for you.
// Stops when the API says there are no more, which is the only correct test: a
// full page can still be the last one, and a short page can still have a
// cursor.
//
//	for property, err := range skautik.AllInquiries(ctx, skautik.Inquiries.ListInquiries(ctx)) {
//		if err != nil {
//			return err
//		}
//		fmt.Println(property.Title)
//	}
func AllInquiries(request ApiListInquiriesRequest) iter.Seq2[Inquiry, error] {
	return func(yield func(Inquiry, error) bool) {
		cursor := ""

		for {
			page, _, err := request.Cursor(cursor).Execute()
			if err != nil {
				var empty Inquiry
				yield(empty, err)
				return
			}

			for _, record := range page.Data {
				if !yield(record, nil) {
					return
				}
			}

			// HasMore is required on a page, so it is a value rather than a
			// pointer: only the presence of meta itself needs checking.
			if page.Meta == nil || !page.Meta.HasMore {
				return
			}
			next := page.Meta.GetNextCursor()
			// A cursor that does not move would page for ever over one page,
			// which is a server fault and should not become a hung client.
			if next == "" || next == cursor {
				return
			}
			cursor = next
		}
	}
}

// AllProperties yields every record, following the cursor.
//
// The same request as ListProperties, with the paging done for you.
// Stops when the API says there are no more, which is the only correct test: a
// full page can still be the last one, and a short page can still have a
// cursor.
//
//	for property, err := range skautik.AllProperties(ctx, skautik.Properties.ListProperties(ctx)) {
//		if err != nil {
//			return err
//		}
//		fmt.Println(property.Title)
//	}
func AllProperties(request ApiListPropertiesRequest) iter.Seq2[Property, error] {
	return func(yield func(Property, error) bool) {
		cursor := ""

		for {
			page, _, err := request.Cursor(cursor).Execute()
			if err != nil {
				var empty Property
				yield(empty, err)
				return
			}

			for _, record := range page.Data {
				if !yield(record, nil) {
					return
				}
			}

			// HasMore is required on a page, so it is a value rather than a
			// pointer: only the presence of meta itself needs checking.
			if page.Meta == nil || !page.Meta.HasMore {
				return
			}
			next := page.Meta.GetNextCursor()
			// A cursor that does not move would page for ever over one page,
			// which is a server fault and should not become a hung client.
			if next == "" || next == cursor {
				return
			}
			cursor = next
		}
	}
}
