// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package skautik

// Client is the Skautik API.
//
//	skautik := skautik.New("sk_live_...")
//
//	page, _, err := skautik.Properties.ListProperties(ctx).
//		City("Berlin").
//		MaxPrice(750000).
//		Execute()
//
// Each field is the generated service for that resource, so everything the
// client can do is reachable from here without knowing which file it lives in.
type Client struct {
	// Endpoints about your key rather than about property.
	Account *AccountAndStatusAPIService

	// Bulk extracts for volumes that would be unreasonable to page through. An export is asynchronous: you request one, we build it, and you fetch the file when it is ready.
	Exports *ExportsAPIService

	// Transform a photograph you have already uploaded: stage an empty room, remove clutter, or correct how a picture was taken. Each request is queued and produced in the background.
	Generations *ImageGenerationsAPIService

	// Move inventory in from whatever system already holds it. A one-off import handles a migration; an import source keeps a CRM and Skautik in step indefinitely.
	Imports *ImportsAPIService

	// Enquiries people have made about your properties, and the state you have moved each one to. Scoped to the properties your organisation owns: an enquiry belongs to whoever owns the property it is about.
	Inquiries *InquiriesAPIService

	// Where we have coverage, how each market is subdivided, and the aggregate statistics computed across it.
	Markets *MarketsAPIService

	// The catalogue, and your own inventory within it. Read endpoints span everything we hold; write endpoints only ever touch records your organisation published.
	Properties *PropertiesAPIService

	// Subscribe to changes rather than polling for them. A webhook costs nothing against your request quota, which makes it much cheaper than re-reading a market on a timer.
	Webhooks *WebhooksAPIService

	// API is the generated client underneath, for anything this does not cover.
	API *APIClient
}

// New returns a client authenticated with an API key.
func New(apiKey string, options ...Option) *Client {
	configuration := NewConfiguration()
	configuration.AddDefaultHeader("Authorization", "Bearer "+apiKey)

	for _, option := range options {
		option(configuration)
	}

	return wrap(NewAPIClient(configuration))
}

// Option adjusts the configuration before the client is built.
type Option func(*Configuration)

// WithServer points the client at a different base URL, for a staging
// environment or a local one.
func WithServer(url string) Option {
	return func(configuration *Configuration) {
		configuration.Servers = ServerConfigurations{{URL: url}}
	}
}

// WithUserAgent names the calling application, which is what appears in the
// logs when somebody asks whose traffic this is.
func WithUserAgent(agent string) Option {
	return func(configuration *Configuration) {
		configuration.UserAgent = agent
	}
}

func wrap(generated *APIClient) *Client {
	return &Client{
		Account: generated.AccountAndStatusAPI,
		Exports: generated.ExportsAPI,
		Generations: generated.ImageGenerationsAPI,
		Imports: generated.ImportsAPI,
		Inquiries: generated.InquiriesAPI,
		Markets: generated.MarketsAPI,
		Properties: generated.PropertiesAPI,
		Webhooks: generated.WebhooksAPI,
		API: generated,
	}
}
